# This is a basic workflow that is manually triggered

name: Update data

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
